/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ajit_validation.g
 *     -                            On : 2021-03-18 04:49:14
 *     -                 for the lexer : ajit_validationLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
ajit_validationLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pajit_validationLexer, which is returned from a call to ajit_validationLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pajit_validationLexer are  as follows:
 *
 *  - 
 void
      pajit_validationLexer->A(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->C(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->CPU(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->EQUAL(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->F(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->G(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->I(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->L(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->M(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->N(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->O(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->P(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->R(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->S(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->T(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->U(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->W(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->X(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->Y(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->Z(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->T__35(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->T__36(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->VALUE(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->COMMENT(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->WS(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->Integer(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->Binary(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->Hexadecimal(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->BinaryPrefix(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->HexadecimalPrefix(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->DecimalDigit(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->HexDigit(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->BinaryDigit(pajit_validationLexer)
 *  - 
 void
      pajit_validationLexer->Tokens(pajit_validationLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_ajit_validationLexer_H
#define _ajit_validationLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct ajit_validationLexer_Ctx_struct ajit_validationLexer, * pajit_validationLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
ajit_validationLexer

 */
struct ajit_validationLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mA)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mC)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mCPU)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mEQUAL)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mF)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mG)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mI)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mL)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mM)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mN)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mO)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mP)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mR)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mS)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mT)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mU)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mW)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mX)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mY)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mZ)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mT__35)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mT__36)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mVALUE)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mInteger)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mBinary)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mHexadecimal)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mBinaryPrefix)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mHexadecimalPrefix)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mDecimalDigit)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mHexDigit)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mBinaryDigit)	(struct ajit_validationLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct ajit_validationLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct ajit_validationLexer_Ctx_struct * ctx);
    void	    (*free)   (struct ajit_validationLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pajit_validationLexer ajit_validationLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pajit_validationLexer ajit_validationLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__35      35
#define T__36      36
#define A      4
#define Binary      5
#define BinaryDigit      6
#define BinaryPrefix      7
#define C      8
#define COMMENT      9
#define CPU      10
#define DecimalDigit      11
#define EQUAL      12
#define F      13
#define G      14
#define HexDigit      15
#define Hexadecimal      16
#define HexadecimalPrefix      17
#define I      18
#define Integer      19
#define L      20
#define M      21
#define N      22
#define O      23
#define P      24
#define R      25
#define S      26
#define T      27
#define U      28
#define VALUE      29
#define W      30
#define WS      31
#define X      32
#define Y      33
#define Z      34
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for ajit_validationLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
