// swizzler.h
//
// Model for the swizzler for shuffling memory addresses for use in hardware security
//
// AUTHOR : Manan Garg

#include <stdint.h>
#include <stdio.h>

#ifndef swizzler_h___
#define  swizzler_h___
#define queue_size 2048
#define memory_size 8192
  #define Cth 2
#define L 4294967296 // (2^32) 
  #define no_sets 3
#define set_size 128
#define mp no_sets * set_size

typedef struct __SwizzlerRecord {
	// mapping FIFO queue which stores the pairs of addresses that are swapped
	//   Let x = a[p][0] and y = a[p][1]
	//   Then whenever the processor generates an access to x
	//     the swizzler will remap it to y and the location y
	//     is accessed.
	uint64_t a[queue_size][2]; 
	
	// queue read/write pointers.
	int front_a, rear_a; 

	//
	//  Set associative memory, which is used to maintain
	//  a table  with address being the tags and
	//  the lc, C arrays below as the data stored with the tag.
	//  
	//  When queried with address x, the memory is accessed, and
	//    if there is a hit, then the lc and C numbers are
	//    returned.
	//  
	//    if there is a miss, then the memory kicks out an entry
	//    based on the lc array below and inserts the query address
	//
	// 
	uint64_t M[no_sets][set_size]; // Defines the Memory. Array M stores stores mp addresses as integers

	//
	// Data associated with addresses in the set associative memory.
	//
	// lc[x] = age of the address in memory (timestamp at entry time).
	uint64_t lc[mp]; 
	// C[x] = number of times an address has been accessed.
	uint64_t C[mp]; 
	// Most rarelu used index in a set.
	uint64_t LC[no_sets]; 
} SwizzlerRecord;


// initialize internal data structures..
void initSwizzler(SwizzlerRecord* sr);

// Function to add a pair of elements (num1, num2) to the queue and storing the
// removed pair of elements (if queue is full) in (old_num1, old_num2)
void queue_in(uint64_t (*queue)[2], int* front, int* rear, uint64_t num1, uint64_t num2, uint64_t* old_num1, uint64_t* old_num2);

// Main swizzling function: Arguments
//  sr = Swizzler data structure
//  read_write_bar = 1 on read, 0 on write.
//  address = root address generated by the processor (l2 miss).
//  dword_h, dword_l = pointers to quadword (used for write data and read data, hence pointers).
//
void processAddress (SwizzlerRecord* sr, 
			uint8_t read_write_bar,
			uint64_t address, 
			uint64_t* dword_h, 
			uint64_t* dword_l);


#endif
