#include <stdint.h>
#include <stdio.h>

#ifndef swizzler_h___
#define  swizzler_h___
#define queue_size 4096
#define memory_size 2048
#define Cth 3
#define L 50 
#define mp 256
#define no_sets 2
#define set_size 128

typedef struct __SwizzlerRecord {
	// mapping FIFO queue which stores the pairs of addresses that are swapped
	//   Let x = a[p][0] and y = a[p][1]
	//   Then whenever the processor generates an access to x
	//     the swizzler will remap it to y and the location y
	//     is accessed.
	uint64_t a[queue_size][2]; 
	
	// queue read/write pointers.
	int front_a, rear_a; 

	//
	//  Set associative memory, which is used to maintain
	//  a table  with address being the tags and
	//  the lc, C arrays below as the data stored with the tag.
	//  
	//  When queried with address x, the memory is accessed, and
	//    if there is a hit, then the lc and C numbers are
	//    returned.
	//  
	//    if there is a miss, then the memory kicks out an entry
	//    based on the lc array below and inserts the query address
	//
	// 
	uint64_t M[no_sets][set_size]; // Defines the Memory. Array M stores stores mp addresses as integers

	//
	// Data associated with addresses in the set associative memory.
	//
	// lc[x] = age of the address in memory (timestamp at entry time).
	uint64_t lc[mp]; 
	// C[x] = number of times an address has been accessed.
	uint64_t C[mp]; 
	// Most rarelu used index in a set.
	uint64_t LC[no_sets]; 
} SwizzlerRecord;


// initialize internal data structures..
void initSwizzler(SwizzlerRecord* sr);

// Arguments
//  sr = Swizzler data structure
//  read_write_bar = 1 on read, 0 on write.
//  address = root address generated by the processor (l2 miss).
//  dword_h, dword_l = pointers to quadword (used for write data and read data, hence pointers).
//
int processAddress (SwizzlerRecord* sr, 
			uint8_t read_write_bar,
			uint64_t address, 
			uint64_t* dword_h, 
			uint64_t* dword_l);

/*
			uint64_t* newly_mapped_address, 
			uint64_t* revert_p, 
			uint64_t* revert_s, 
			uint64_t* s);
*/


// swap the locations in memory.
int swapLocations (uint64_t address_0, uint64_t address_1);

#endif
