import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})
COMPILATION_FLAGS=' -g '


AHIR_RELEASE=os.environ['AHIR_RELEASE']
env.Append(CPPPATH = './src/:./include:')

#AHIR-related
env.Append(CPPPATH =  "./include/:" + "./src/:")

# create a library for the console :
#env.SharedLibrary('./lib/libCharClientServer', Glob('src/*.c'), CCFLAGS=COMPILATION_FLAGS)
env.Library('./lib/libCharClientServer', Glob('src/*.c'), CCFLAGS=COMPILATION_FLAGS)
env.Program('./bin/client', 'test/client.c', CCFLAGS=COMPILATION_FLAGS, LINKFLAGS='-g', LIBS='CharClientServer',LIBPATH='./lib')
env.Program('./bin/server', 'test/server.c', CCFLAGS=COMPILATION_FLAGS, LINKFLAGS='-g', LIBS='CharClientServer',LIBPATH='./lib')


