import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})
COMPILATION_FLAGS=' -g '

env.Append(CPPPATH = './src/:./include:')


# create a library for the console :
env.Library('./lib/libriffa_dummy', Glob('src/*.c'), CCFLAGS=COMPILATION_FLAGS)


