#!/bin/sh
# devtmpfs does not get automounted for initramfs
echo "init shell script called ..."
#echo "running /bin/mount -t devtmpfs devtmpfs /dev"
#/bin/mount -t devtmpfs devtmpfs /dev
echo "running exec 0</dev/console"
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console
echo "running exec /sbin/init "
exec /sbin/init $*
