/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ajit_validation.g
 *     -                            On : 2021-03-18 04:49:14
 *     -                 for the lexer : ajit_validationLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ajit_validationLexer.h"
/* ----------------------------------------- */


/** String literals used by ajit_validationLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x61, 0x73, 0x69,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x70, 0x63,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x63, 0x70, 0x75,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x6E, 0x70, 0x63,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x70, 0x73, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x63, 0x70, 0x73, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x66, 0x70, 0x73, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x74, 0x62, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x6D, 0x6D, 0x75,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x77, 0x69, 0x6D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x61, 0x73, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x2F, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x2F, 0x2A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x2A, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x30, 0x62,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_16[]  = { 0x30, 0x42,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_17[]  = { 0x30, 0x78,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_18[]  = { 0x30, 0x58,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pajit_validationLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pajit_validationLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pajit_validationLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pajit_validationLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mA    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mC    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mCPU    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mEQUAL    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mF    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mG    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mI    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mL    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mM    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mN    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mO    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mP    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mR    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mS    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mT    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mU    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mW    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mX    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mY    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mZ    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mT__35    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mT__36    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mVALUE    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mCOMMENT    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mInteger    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mBinary    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mHexadecimal    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mBinaryPrefix    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mHexadecimalPrefix    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mDecimalDigit    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mHexDigit    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mBinaryDigit    (pajit_validationLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pajit_validationLexer ctx);
static void	ajit_validationLexerFree(pajit_validationLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
ajit_validationLexerFree  (pajit_validationLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
ajit_validationLexerReset (pajit_validationLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ajit_validation.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called ajit_validationLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pajit_validationLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pajit_validationLexer ajit_validationLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return ajit_validationLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called ajit_validationLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pajit_validationLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pajit_validationLexer ajit_validationLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pajit_validationLexer ctx; // Context structure we will build and return

    ctx = (pajit_validationLexer) ANTLR3_CALLOC(1, sizeof(ajit_validationLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ajit_validationLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our ajit_validationLexer interface
     */
    ctx->mA	= mA;
    ctx->mC	= mC;
    ctx->mCPU	= mCPU;
    ctx->mEQUAL	= mEQUAL;
    ctx->mF	= mF;
    ctx->mG	= mG;
    ctx->mI	= mI;
    ctx->mL	= mL;
    ctx->mM	= mM;
    ctx->mN	= mN;
    ctx->mO	= mO;
    ctx->mP	= mP;
    ctx->mR	= mR;
    ctx->mS	= mS;
    ctx->mT	= mT;
    ctx->mU	= mU;
    ctx->mW	= mW;
    ctx->mX	= mX;
    ctx->mY	= mY;
    ctx->mZ	= mZ;
    ctx->mT__35	= mT__35;
    ctx->mT__36	= mT__36;
    ctx->mVALUE	= mVALUE;
    ctx->mCOMMENT	= mCOMMENT;
    ctx->mWS	= mWS;
    ctx->mInteger	= mInteger;
    ctx->mBinary	= mBinary;
    ctx->mHexadecimal	= mHexadecimal;
    ctx->mBinaryPrefix	= mBinaryPrefix;
    ctx->mHexadecimalPrefix	= mHexadecimalPrefix;
    ctx->mDecimalDigit	= mDecimalDigit;
    ctx->mHexDigit	= mHexDigit;
    ctx->mBinaryDigit	= mBinaryDigit;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= ajit_validationLexerFree;
    ctx->reset          = ajit_validationLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:3: ( 'asi' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start A
 *
 * Looks to match the characters the constitute the token A
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mA(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = A;


    // ajit_validation.g:7:3: ( 'asi' )
    // ajit_validation.g:7:5: 'asi'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleAEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleAEx; /* Prevent compiler warnings */
    ruleAEx: ;

}
// $ANTLR end A

//   Comes from: 8:3: ( 'pc' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start C
 *
 * Looks to match the characters the constitute the token C
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mC(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = C;


    // ajit_validation.g:8:3: ( 'pc' )
    // ajit_validation.g:8:5: 'pc'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleCEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCEx; /* Prevent compiler warnings */
    ruleCEx: ;

}
// $ANTLR end C

//   Comes from: 9:5: ( 'cpu' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CPU
 *
 * Looks to match the characters the constitute the token CPU
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCPU(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CPU;


    // ajit_validation.g:9:5: ( 'cpu' )
    // ajit_validation.g:9:7: 'cpu'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleCPUEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCPUEx; /* Prevent compiler warnings */
    ruleCPUEx: ;

}
// $ANTLR end CPU

//   Comes from: 10:7: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQUAL
 *
 * Looks to match the characters the constitute the token EQUAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQUAL(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EQUAL;


    // ajit_validation.g:10:7: ( '=' )
    // ajit_validation.g:10:9: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleEQUALEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEQUALEx; /* Prevent compiler warnings */
    ruleEQUALEx: ;

}
// $ANTLR end EQUAL

//   Comes from: 11:3: ( 'f' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start F
 *
 * Looks to match the characters the constitute the token F
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mF(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = F;


    // ajit_validation.g:11:3: ( 'f' )
    // ajit_validation.g:11:5: 'f'
    {
        MATCHC('f');
        if  (HASEXCEPTION())
        {
            goto ruleFEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleFEx; /* Prevent compiler warnings */
    ruleFEx: ;

}
// $ANTLR end F

//   Comes from: 12:3: ( 'g' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start G
 *
 * Looks to match the characters the constitute the token G
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mG(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = G;


    // ajit_validation.g:12:3: ( 'g' )
    // ajit_validation.g:12:5: 'g'
    {
        MATCHC('g');
        if  (HASEXCEPTION())
        {
            goto ruleGEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleGEx; /* Prevent compiler warnings */
    ruleGEx: ;

}
// $ANTLR end G

//   Comes from: 13:3: ( 'i' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start I
 *
 * Looks to match the characters the constitute the token I
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mI(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = I;


    // ajit_validation.g:13:3: ( 'i' )
    // ajit_validation.g:13:5: 'i'
    {
        MATCHC('i');
        if  (HASEXCEPTION())
        {
            goto ruleIEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIEx; /* Prevent compiler warnings */
    ruleIEx: ;

}
// $ANTLR end I

//   Comes from: 14:3: ( 'l' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start L
 *
 * Looks to match the characters the constitute the token L
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mL(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = L;


    // ajit_validation.g:14:3: ( 'l' )
    // ajit_validation.g:14:5: 'l'
    {
        MATCHC('l');
        if  (HASEXCEPTION())
        {
            goto ruleLEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLEx; /* Prevent compiler warnings */
    ruleLEx: ;

}
// $ANTLR end L

//   Comes from: 15:3: ( 'm' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start M
 *
 * Looks to match the characters the constitute the token M
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mM(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = M;


    // ajit_validation.g:15:3: ( 'm' )
    // ajit_validation.g:15:5: 'm'
    {
        MATCHC('m');
        if  (HASEXCEPTION())
        {
            goto ruleMEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMEx; /* Prevent compiler warnings */
    ruleMEx: ;

}
// $ANTLR end M

//   Comes from: 16:3: ( 'npc' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start N
 *
 * Looks to match the characters the constitute the token N
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mN(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = N;


    // ajit_validation.g:16:3: ( 'npc' )
    // ajit_validation.g:16:5: 'npc'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleNEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNEx; /* Prevent compiler warnings */
    ruleNEx: ;

}
// $ANTLR end N

//   Comes from: 17:3: ( 'o' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start O
 *
 * Looks to match the characters the constitute the token O
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mO(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = O;


    // ajit_validation.g:17:3: ( 'o' )
    // ajit_validation.g:17:5: 'o'
    {
        MATCHC('o');
        if  (HASEXCEPTION())
        {
            goto ruleOEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOEx; /* Prevent compiler warnings */
    ruleOEx: ;

}
// $ANTLR end O

//   Comes from: 18:3: ( 'psr' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start P
 *
 * Looks to match the characters the constitute the token P
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mP(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = P;


    // ajit_validation.g:18:3: ( 'psr' )
    // ajit_validation.g:18:5: 'psr'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto rulePEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePEx; /* Prevent compiler warnings */
    rulePEx: ;

}
// $ANTLR end P

//   Comes from: 19:3: ( 'cpsr' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start R
 *
 * Looks to match the characters the constitute the token R
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mR(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = R;


    // ajit_validation.g:19:3: ( 'cpsr' )
    // ajit_validation.g:19:5: 'cpsr'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleREx; /* Prevent compiler warnings */
    ruleREx: ;

}
// $ANTLR end R

//   Comes from: 20:3: ( 'fpsr' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start S
 *
 * Looks to match the characters the constitute the token S
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mS(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = S;


    // ajit_validation.g:20:3: ( 'fpsr' )
    // ajit_validation.g:20:5: 'fpsr'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleSEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSEx; /* Prevent compiler warnings */
    ruleSEx: ;

}
// $ANTLR end S

//   Comes from: 21:3: ( 'tbr' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T
 *
 * Looks to match the characters the constitute the token T
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T;


    // ajit_validation.g:21:3: ( 'tbr' )
    // ajit_validation.g:21:5: 'tbr'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleTEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleTEx; /* Prevent compiler warnings */
    ruleTEx: ;

}
// $ANTLR end T

//   Comes from: 22:3: ( 'mmu' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start U
 *
 * Looks to match the characters the constitute the token U
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mU(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = U;


    // ajit_validation.g:22:3: ( 'mmu' )
    // ajit_validation.g:22:5: 'mmu'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleUEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleUEx; /* Prevent compiler warnings */
    ruleUEx: ;

}
// $ANTLR end U

//   Comes from: 23:3: ( 'wim' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start W
 *
 * Looks to match the characters the constitute the token W
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mW(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = W;


    // ajit_validation.g:23:3: ( 'wim' )
    // ajit_validation.g:23:5: 'wim'
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleWEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWEx; /* Prevent compiler warnings */
    ruleWEx: ;

}
// $ANTLR end W

//   Comes from: 24:3: ( 'x' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start X
 *
 * Looks to match the characters the constitute the token X
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mX(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = X;


    // ajit_validation.g:24:3: ( 'x' )
    // ajit_validation.g:24:5: 'x'
    {
        MATCHC('x');
        if  (HASEXCEPTION())
        {
            goto ruleXEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleXEx; /* Prevent compiler warnings */
    ruleXEx: ;

}
// $ANTLR end X

//   Comes from: 25:3: ( 'y' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Y
 *
 * Looks to match the characters the constitute the token Y
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mY(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = Y;


    // ajit_validation.g:25:3: ( 'y' )
    // ajit_validation.g:25:5: 'y'
    {
        MATCHC('y');
        if  (HASEXCEPTION())
        {
            goto ruleYEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleYEx; /* Prevent compiler warnings */
    ruleYEx: ;

}
// $ANTLR end Y

//   Comes from: 26:3: ( 'asr' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Z
 *
 * Looks to match the characters the constitute the token Z
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mZ(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = Z;


    // ajit_validation.g:26:3: ( 'asr' )
    // ajit_validation.g:26:5: 'asr'
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleZEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleZEx; /* Prevent compiler warnings */
    ruleZEx: ;

}
// $ANTLR end Z

//   Comes from: 27:7: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__35
 *
 * Looks to match the characters the constitute the token T__35
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__35(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__35;


    // ajit_validation.g:27:7: ( '[' )
    // ajit_validation.g:27:9: '['
    {
        MATCHC('[');
        if  (HASEXCEPTION())
        {
            goto ruleT__35Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__35Ex; /* Prevent compiler warnings */
    ruleT__35Ex: ;

}
// $ANTLR end T__35

//   Comes from: 28:7: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__36
 *
 * Looks to match the characters the constitute the token T__36
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__36(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__36;


    // ajit_validation.g:28:7: ( ']' )
    // ajit_validation.g:28:9: ']'
    {
        MATCHC(']');
        if  (HASEXCEPTION())
        {
            goto ruleT__36Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__36Ex; /* Prevent compiler warnings */
    ruleT__36Ex: ;

}
// $ANTLR end T__36

//   Comes from: 76:7: ( Integer | Binary | Hexadecimal )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start VALUE
 *
 * Looks to match the characters the constitute the token VALUE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mVALUE(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = VALUE;


    {
        //  ajit_validation.g:76:7: ( Integer | Binary | Hexadecimal )

        ANTLR3_UINT32 alt1;

        alt1=3;

        switch ( LA(1) )
        {
        case '0':
        	{
        		switch ( LA(2) )
        		{
        		case 'B':
        		case 'b':
        			{
        				alt1=2;
        			}
        		    break;
        		case 'X':
        		case 'x':
        			{
        				alt1=3;
        			}
        		    break;

        		default:
        		    alt1=1;
        		}

        	}
            break;
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt1=1;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 1;
            EXCEPTION->state        = 0;


            goto ruleVALUEEx;

        }

        switch (alt1)
        {
    	case 1:
    	    // ajit_validation.g:76:9: Integer
    	    {
    	        /* 76:9: Integer */
    	        mInteger(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleVALUEEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // ajit_validation.g:76:19: Binary
    	    {
    	        /* 76:19: Binary */
    	        mBinary(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleVALUEEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // ajit_validation.g:76:28: Hexadecimal
    	    {
    	        /* 76:28: Hexadecimal */
    	        mHexadecimal(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleVALUEEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleVALUEEx; /* Prevent compiler warnings */
    ruleVALUEEx: ;

}
// $ANTLR end VALUE

//   Comes from: 83:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' | '/*' ( options {greedy=false; } : . )* '*/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMENT
 *
 * Looks to match the characters the constitute the token COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMENT(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMENT;


    {
        //  ajit_validation.g:83:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' | '/*' ( options {greedy=false; } : . )* '*/' )

        ANTLR3_UINT32 alt5;

        alt5=2;

        switch ( LA(1) )
        {
        case '/':
        	{
        		switch ( LA(2) )
        		{
        		case '/':
        			{
        				alt5=1;
        			}
        		    break;
        		case '*':
        			{
        				alt5=2;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 5;
        		    EXCEPTION->state        = 1;


        		    goto ruleCOMMENTEx;

        		}

        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 5;
            EXCEPTION->state        = 0;


            goto ruleCOMMENTEx;

        }

        switch (alt5)
        {
    	case 1:
    	    // ajit_validation.g:83:5: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
    	    {
    	        MATCHS(lit_12);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleCOMMENTEx;
    	        }




    	        // ajit_validation.g:83:10: (~ ( '\\n' | '\\r' ) )*

    	        for (;;)
    	        {
    	            int alt2=2;
    	            {
    	               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                */
    	                int LA2_0 = LA(1);
    	                if ( (((LA2_0 >= 0x0000) && (LA2_0 <= '\t')) || ((LA2_0 >= 0x000B) && (LA2_0 <= '\f')) || ((LA2_0 >= 0x000E) && (LA2_0 <= 0xFFFF))))
    	                {
    	                    alt2=1;
    	                }

    	            }
    	            switch (alt2)
    	            {
    	        	case 1:
    	        	    // ajit_validation.g:
    	        	    {
    	        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= 0xFFFF)) )
    	        	        {
    	        	            CONSUME();
    	        	        }
    	        	        else
    	        	        {
    	        	            CONSTRUCTEX();
    	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	            LRECOVER();
    	        	            goto ruleCOMMENTEx;
    	        	        }


    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop2;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop2: ; /* Jump out to here if this rule does not match */


    	        // ajit_validation.g:83:24: ( '\\r' )?
    	        {
    	            int alt3=2;
    	            switch ( LA(1) )
    	            {
    	                case '\r':
    	                	{
    	                		alt3=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt3)
    	            {
    	        	case 1:
    	        	    // ajit_validation.g:83:24: '\\r'
    	        	    {
    	        	        MATCHC('\r');
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleCOMMENTEx;
    	        	        }


    	        	    }
    	        	    break;

    	            }
    	        }

    	        MATCHC('\n');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleCOMMENTEx;
    	        }


    	        {
    	            LEXSTATE->channel=HIDDEN;
    	        }


    	    }
    	    break;
    	case 2:
    	    // ajit_validation.g:84:5: '/*' ( options {greedy=false; } : . )* '*/'
    	    {
    	        MATCHS(lit_13);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleCOMMENTEx;
    	        }




    	        // ajit_validation.g:84:10: ( options {greedy=false; } : . )*

    	        for (;;)
    	        {
    	            int alt4=2;
    	            {
    	               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                */
    	                int LA4_0 = LA(1);
    	                if ( (LA4_0 == '*'))
    	                {
    	                    {
    	                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                        */
    	                        int LA4_1 = LA(2);
    	                        if ( (LA4_1 == '/'))
    	                        {
    	                            alt4=2;
    	                        }
    	                        else if ( (((LA4_1 >= 0x0000) && (LA4_1 <= '.')) || ((LA4_1 >= '0') && (LA4_1 <= 0xFFFF))))
    	                        {
    	                            alt4=1;
    	                        }

    	                    }
    	                }
    	                else if ( (((LA4_0 >= 0x0000) && (LA4_0 <= ')')) || ((LA4_0 >= '+') && (LA4_0 <= 0xFFFF))))
    	                {
    	                    alt4=1;
    	                }

    	            }
    	            switch (alt4)
    	            {
    	        	case 1:
    	        	    // ajit_validation.g:84:38: .
    	        	    {
    	        	        MATCHANY();
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleCOMMENTEx;
    	        	        }


    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop4;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop4: ; /* Jump out to here if this rule does not match */


    	        MATCHS(lit_14);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleCOMMENTEx;
    	        }




    	        {
    	            LEXSTATE->channel=HIDDEN;
    	        }


    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOMMENTEx; /* Prevent compiler warnings */
    ruleCOMMENTEx: ;

}
// $ANTLR end COMMENT

//   Comes from: 89:5: ( ( '\\n' | '\\t' | '\\r' | ' ' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // ajit_validation.g:89:5: ( ( '\\n' | '\\t' | '\\r' | ' ' )+ )
    // ajit_validation.g:89:9: ( '\\n' | '\\t' | '\\r' | ' ' )+
    {
        // ajit_validation.g:89:9: ( '\\n' | '\\t' | '\\r' | ' ' )+
        {
            int cnt6=0;

            for (;;)
            {
                int alt6=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\r':
        	case ' ':
        		{
        			alt6=1;
        		}
        	    break;

        	}

        	switch (alt6)
        	{
        	    case 1:
        	        // ajit_validation.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt6 >= 1 )
        		{
        		    goto loop6;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt6++;
            }
            loop6: ;	/* Jump to here if this rule does not match */
        }

        {
            LEXSTATE->channel=HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

//   Comes from: 96:18: ( '0' | '1' .. '9' ( DecimalDigit )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Integer
 *
 * Looks to match the characters the constitute the token Integer
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mInteger(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;


    {
        //  ajit_validation.g:96:18: ( '0' | '1' .. '9' ( DecimalDigit )* )

        ANTLR3_UINT32 alt8;

        alt8=2;

        switch ( LA(1) )
        {
        case '0':
        	{
        		alt8=1;
        	}
            break;
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt8=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 8;
            EXCEPTION->state        = 0;


            goto ruleIntegerEx;

        }

        switch (alt8)
        {
    	case 1:
    	    // ajit_validation.g:96:20: '0'
    	    {
    	        MATCHC('0');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleIntegerEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // ajit_validation.g:96:26: '1' .. '9' ( DecimalDigit )*
    	    {
    	        MATCHRANGE('1', '9');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleIntegerEx;
    	        }


    	        // ajit_validation.g:96:35: ( DecimalDigit )*

    	        for (;;)
    	        {
    	            int alt7=2;
    	            switch ( LA(1) )
    	            {
    	            case '0':
    	            case '1':
    	            case '2':
    	            case '3':
    	            case '4':
    	            case '5':
    	            case '6':
    	            case '7':
    	            case '8':
    	            case '9':
    	            	{
    	            		alt7=1;
    	            	}
    	                break;

    	            }

    	            switch (alt7)
    	            {
    	        	case 1:
    	        	    // ajit_validation.g:
    	        	    {
    	        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	        {
    	        	            CONSUME();
    	        	        }
    	        	        else
    	        	        {
    	        	            CONSTRUCTEX();
    	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	            LRECOVER();
    	        	            goto ruleIntegerEx;
    	        	        }


    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop7;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop7: ; /* Jump out to here if this rule does not match */


    	    }
    	    break;

        }
    }

    // This is where rules clean up and exit
    //
    goto ruleIntegerEx; /* Prevent compiler warnings */
    ruleIntegerEx: ;

}
// $ANTLR end Integer

//   Comes from: 97:17: ( BinaryPrefix ( BinaryDigit )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Binary
 *
 * Looks to match the characters the constitute the token Binary
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBinary(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;


    // ajit_validation.g:97:17: ( BinaryPrefix ( BinaryDigit )+ )
    // ajit_validation.g:97:20: BinaryPrefix ( BinaryDigit )+
    {
        /* 97:20: BinaryPrefix ( BinaryDigit )+ */
        mBinaryPrefix(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleBinaryEx;
        }



        // ajit_validation.g:97:33: ( BinaryDigit )+
        {
            int cnt9=0;

            for (;;)
            {
                int alt9=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        		{
        			alt9=1;
        		}
        	    break;

        	}

        	switch (alt9)
        	{
        	    case 1:
        	        // ajit_validation.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '1')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleBinaryEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt9 >= 1 )
        		{
        		    goto loop9;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleBinaryEx;
        	}
        	cnt9++;
            }
            loop9: ;	/* Jump to here if this rule does not match */
        }

    }


    // This is where rules clean up and exit
    //
    goto ruleBinaryEx; /* Prevent compiler warnings */
    ruleBinaryEx: ;

}
// $ANTLR end Binary

//   Comes from: 98:28: ( HexadecimalPrefix ( HexDigit )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Hexadecimal
 *
 * Looks to match the characters the constitute the token Hexadecimal
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mHexadecimal(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;


    // ajit_validation.g:98:28: ( HexadecimalPrefix ( HexDigit )+ )
    // ajit_validation.g:98:30: HexadecimalPrefix ( HexDigit )+
    {
        /* 98:30: HexadecimalPrefix ( HexDigit )+ */
        mHexadecimalPrefix(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleHexadecimalEx;
        }



        // ajit_validation.g:98:47: ( HexDigit )+
        {
            int cnt10=0;

            for (;;)
            {
                int alt10=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        	case 'A':
        	case 'B':
        	case 'C':
        	case 'D':
        	case 'E':
        	case 'F':
        	case 'a':
        	case 'b':
        	case 'c':
        	case 'd':
        	case 'e':
        	case 'f':
        		{
        			alt10=1;
        		}
        	    break;

        	}

        	switch (alt10)
        	{
        	    case 1:
        	        // ajit_validation.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'F')) || ((LA(1) >= 'a') && (LA(1) <= 'f')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleHexadecimalEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt10 >= 1 )
        		{
        		    goto loop10;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleHexadecimalEx;
        	}
        	cnt10++;
            }
            loop10: ;	/* Jump to here if this rule does not match */
        }

    }


    // This is where rules clean up and exit
    //
    goto ruleHexadecimalEx; /* Prevent compiler warnings */
    ruleHexadecimalEx: ;

}
// $ANTLR end Hexadecimal

//   Comes from: 99:32: ( ( '0b' | '0B' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BinaryPrefix
 *
 * Looks to match the characters the constitute the token BinaryPrefix
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBinaryPrefix(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;


    // ajit_validation.g:99:32: ( ( '0b' | '0B' ) )
    // ajit_validation.g:99:34: ( '0b' | '0B' )
    {
        // ajit_validation.g:99:34: ( '0b' | '0B' )
        {
            int alt11=2;
            switch ( LA(1) )
            {
            case '0':
            	{
            		switch ( LA(2) )
            		{
            		case 'b':
            			{
            				alt11=1;
            			}
            		    break;
            		case 'B':
            			{
            				alt11=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 11;
            		    EXCEPTION->state        = 1;


            		    goto ruleBinaryPrefixEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 11;
                EXCEPTION->state        = 0;


                goto ruleBinaryPrefixEx;

            }

            switch (alt11)
            {
        	case 1:
        	    // ajit_validation.g:99:35: '0b'
        	    {
        	        MATCHS(lit_15);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBinaryPrefixEx;
        	        }




        	    }
        	    break;
        	case 2:
        	    // ajit_validation.g:99:42: '0B'
        	    {
        	        MATCHS(lit_16);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBinaryPrefixEx;
        	        }




        	    }
        	    break;

            }
        }

    }


    // This is where rules clean up and exit
    //
    goto ruleBinaryPrefixEx; /* Prevent compiler warnings */
    ruleBinaryPrefixEx: ;

}
// $ANTLR end BinaryPrefix

//   Comes from: 100:32: ( ( '0x' | '0X' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start HexadecimalPrefix
 *
 * Looks to match the characters the constitute the token HexadecimalPrefix
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mHexadecimalPrefix(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;


    // ajit_validation.g:100:32: ( ( '0x' | '0X' ) )
    // ajit_validation.g:100:34: ( '0x' | '0X' )
    {
        // ajit_validation.g:100:34: ( '0x' | '0X' )
        {
            int alt12=2;
            switch ( LA(1) )
            {
            case '0':
            	{
            		switch ( LA(2) )
            		{
            		case 'x':
            			{
            				alt12=1;
            			}
            		    break;
            		case 'X':
            			{
            				alt12=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 12;
            		    EXCEPTION->state        = 1;


            		    goto ruleHexadecimalPrefixEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 12;
                EXCEPTION->state        = 0;


                goto ruleHexadecimalPrefixEx;

            }

            switch (alt12)
            {
        	case 1:
        	    // ajit_validation.g:100:35: '0x'
        	    {
        	        MATCHS(lit_17);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleHexadecimalPrefixEx;
        	        }




        	    }
        	    break;
        	case 2:
        	    // ajit_validation.g:100:42: '0X'
        	    {
        	        MATCHS(lit_18);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleHexadecimalPrefixEx;
        	        }




        	    }
        	    break;

            }
        }

    }


    // This is where rules clean up and exit
    //
    goto ruleHexadecimalPrefixEx; /* Prevent compiler warnings */
    ruleHexadecimalPrefixEx: ;

}
// $ANTLR end HexadecimalPrefix

//   Comes from: 101:26: ( '0' .. '9' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DecimalDigit
 *
 * Looks to match the characters the constitute the token DecimalDigit
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDecimalDigit(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;


    // ajit_validation.g:101:26: ( '0' .. '9' )
    // ajit_validation.g:
    {
        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleDecimalDigitEx;
        }


    }


    // This is where rules clean up and exit
    //
    goto ruleDecimalDigitEx; /* Prevent compiler warnings */
    ruleDecimalDigitEx: ;

}
// $ANTLR end DecimalDigit

//   Comes from: 102:26: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start HexDigit
 *
 * Looks to match the characters the constitute the token HexDigit
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mHexDigit(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;


    // ajit_validation.g:102:26: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
    // ajit_validation.g:
    {
        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'F')) || ((LA(1) >= 'a') && (LA(1) <= 'f')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleHexDigitEx;
        }


    }


    // This is where rules clean up and exit
    //
    goto ruleHexDigitEx; /* Prevent compiler warnings */
    ruleHexDigitEx: ;

}
// $ANTLR end HexDigit

//   Comes from: 103:24: ( ( '0' | '1' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BinaryDigit
 *
 * Looks to match the characters the constitute the token BinaryDigit
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBinaryDigit(pajit_validationLexer ctx)
{
	ANTLR3_UINT32	_type;


    // ajit_validation.g:103:24: ( ( '0' | '1' ) )
    // ajit_validation.g:
    {
        if ( ((LA(1) >= '0') && (LA(1) <= '1')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleBinaryDigitEx;
        }


    }


    // This is where rules clean up and exit
    //
    goto ruleBinaryDigitEx; /* Prevent compiler warnings */
    ruleBinaryDigitEx: ;

}
// $ANTLR end BinaryDigit

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pajit_validationLexer ctx)
{
    {
        //  ajit_validation.g:1:8: ( A | C | CPU | EQUAL | F | G | I | L | M | N | O | P | R | S | T | U | W | X | Y | Z | T__35 | T__36 | VALUE | COMMENT | WS )

        ANTLR3_UINT32 alt13;

        alt13=25;

        switch ( LA(1) )
        {
        case 'a':
        	{
        		switch ( LA(2) )
        		{
        		case 's':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						alt13=1;
        					}
        				    break;
        				case 'r':
        					{
        						alt13=20;
        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 13;
        				    EXCEPTION->state        = 21;


        				    goto ruleTokensEx;

        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 13;
        		    EXCEPTION->state        = 1;


        		    goto ruleTokensEx;

        		}

        	}
            break;
        case 'p':
        	{
        		switch ( LA(2) )
        		{
        		case 'c':
        			{
        				alt13=2;
        			}
        		    break;
        		case 's':
        			{
        				alt13=12;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 13;
        		    EXCEPTION->state        = 2;


        		    goto ruleTokensEx;

        		}

        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) )
        		{
        		case 'p':
        			{
        				switch ( LA(3) )
        				{
        				case 'u':
        					{
        						alt13=3;
        					}
        				    break;
        				case 's':
        					{
        						alt13=13;
        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 13;
        				    EXCEPTION->state        = 24;


        				    goto ruleTokensEx;

        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 13;
        		    EXCEPTION->state        = 3;


        		    goto ruleTokensEx;

        		}

        	}
            break;
        case '=':
        	{
        		alt13=4;
        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) )
        		{
        		case 'p':
        			{
        				alt13=14;
        			}
        		    break;

        		default:
        		    alt13=5;
        		}

        	}
            break;
        case 'g':
        	{
        		alt13=6;
        	}
            break;
        case 'i':
        	{
        		alt13=7;
        	}
            break;
        case 'l':
        	{
        		alt13=8;
        	}
            break;
        case 'm':
        	{
        		switch ( LA(2) )
        		{
        		case 'm':
        			{
        				alt13=16;
        			}
        		    break;

        		default:
        		    alt13=9;
        		}

        	}
            break;
        case 'n':
        	{
        		alt13=10;
        	}
            break;
        case 'o':
        	{
        		alt13=11;
        	}
            break;
        case 't':
        	{
        		alt13=15;
        	}
            break;
        case 'w':
        	{
        		alt13=17;
        	}
            break;
        case 'x':
        	{
        		alt13=18;
        	}
            break;
        case 'y':
        	{
        		alt13=19;
        	}
            break;
        case '[':
        	{
        		alt13=21;
        	}
            break;
        case ']':
        	{
        		alt13=22;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt13=23;
        	}
            break;
        case '/':
        	{
        		alt13=24;
        	}
            break;
        case '\t':
        case '\n':
        case '\r':
        case ' ':
        	{
        		alt13=25;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 13;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt13)
        {
    	case 1:
    	    // ajit_validation.g:1:10: A
    	    {
    	        /* 1:10: A */
    	        mA(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // ajit_validation.g:1:12: C
    	    {
    	        /* 1:12: C */
    	        mC(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // ajit_validation.g:1:14: CPU
    	    {
    	        /* 1:14: CPU */
    	        mCPU(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // ajit_validation.g:1:18: EQUAL
    	    {
    	        /* 1:18: EQUAL */
    	        mEQUAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // ajit_validation.g:1:24: F
    	    {
    	        /* 1:24: F */
    	        mF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // ajit_validation.g:1:26: G
    	    {
    	        /* 1:26: G */
    	        mG(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // ajit_validation.g:1:28: I
    	    {
    	        /* 1:28: I */
    	        mI(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // ajit_validation.g:1:30: L
    	    {
    	        /* 1:30: L */
    	        mL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // ajit_validation.g:1:32: M
    	    {
    	        /* 1:32: M */
    	        mM(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // ajit_validation.g:1:34: N
    	    {
    	        /* 1:34: N */
    	        mN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // ajit_validation.g:1:36: O
    	    {
    	        /* 1:36: O */
    	        mO(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // ajit_validation.g:1:38: P
    	    {
    	        /* 1:38: P */
    	        mP(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // ajit_validation.g:1:40: R
    	    {
    	        /* 1:40: R */
    	        mR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // ajit_validation.g:1:42: S
    	    {
    	        /* 1:42: S */
    	        mS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // ajit_validation.g:1:44: T
    	    {
    	        /* 1:44: T */
    	        mT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // ajit_validation.g:1:46: U
    	    {
    	        /* 1:46: U */
    	        mU(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // ajit_validation.g:1:48: W
    	    {
    	        /* 1:48: W */
    	        mW(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // ajit_validation.g:1:50: X
    	    {
    	        /* 1:50: X */
    	        mX(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // ajit_validation.g:1:52: Y
    	    {
    	        /* 1:52: Y */
    	        mY(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // ajit_validation.g:1:54: Z
    	    {
    	        /* 1:54: Z */
    	        mZ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // ajit_validation.g:1:56: T__35
    	    {
    	        /* 1:56: T__35 */
    	        mT__35(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // ajit_validation.g:1:62: T__36
    	    {
    	        /* 1:62: T__36 */
    	        mT__36(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // ajit_validation.g:1:68: VALUE
    	    {
    	        /* 1:68: VALUE */
    	        mVALUE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // ajit_validation.g:1:74: COMMENT
    	    {
    	        /* 1:74: COMMENT */
    	        mCOMMENT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // ajit_validation.g:1:82: WS
    	    {
    	        /* 1:82: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
