import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})
COMPILATION_FLAGS=' -g '


AJIT_HOME=os.environ['AJIT_PROJECT_HOME']
AHIR_RELEASE=os.environ['AHIR_RELEASE']
env.Append(CPPPATH = './src/:./include:' + AHIR_RELEASE + '/include:')

# create a library for the console :
env.Library('./lib/libuart_interface', Glob('src/*.c'), CCFLAGS=COMPILATION_FLAGS)

LLIBS=" uart_interface pthread "
LLIBPATHS=" ./lib "
env.Program('./bin/sendBinfileOverUart', [ 'util/sendBinFileOverUart.c' ], CCFLAGS=' -g ', LIBS=(Split(LLIBS)), LIBPATH=(Split(LLIBPATHS))); 
env.Program('./bin/calibrateUart', [ 'util/calibrateUart.c'], CCFLAGS=' -g ', LIBS=(Split(LLIBS)), LIBPATH=(Split(LLIBPATHS))); 


