# yaml configuration file for linker/loader of Co-RTOS

Cores: 1  # must agree with the processor used
ThreadsPerCore: 1  # must agree with the processor used

Threads: # name all your programs
  - Functions:
      - ajit_cortos_entry_func_001
      - ajit_cortos_entry_func_010
    StackSizeInKB: 1024


