import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})
COMPILATION_FLAGS = ' -g '

AHIR_RELEASE=os.environ['AHIR_RELEASE']
AJIT_HOME=os.environ['AJIT_PROJECT_HOME']
AJIT_C_REF_MODEL=os.environ['AJIT_C_REF_MODEL']

env.Append(CPPPATH = "./:" + AJIT_C_REF_MODEL + "/common/include:" + AJIT_C_REF_MODEL + "/cpu/include:" + AJIT_C_REF_MODEL + "/memory/include:"  + AJIT_C_REF_MODEL + "/mmu/include:" )
env.Append(CPPPATH = AJIT_C_REF_MODEL + "/rlut/include:")



#AHIR-related
PIPE_HANDLER_INCLUDE=AHIR_RELEASE + "/include"
PIPE_HANDLER_LIBPATH = AHIR_RELEASE + "/lib"
PTHREAD_UTILS = AHIR_RELEASE + "/include"
FUNCTIONLIB_PATH = AHIR_RELEASE + "/functionLibrary/lib"
env.Append(CPPPATH = PIPE_HANDLER_INCLUDE + ":" + PTHREAD_UTILS + ":"  + "./include:")


# create a library for the cache :
env.Library('./lib/libCache', Glob('src/*.c'), CCFLAGS=COMPILATION_FLAGS)

