import os
import sys

env = Environment(ENV = {'PATH' : os.environ['PATH']})
Import('COMPILATION_FLAGS')

AHIR_RELEASE=os.environ['AHIR_RELEASE']
AHIR_INCLUDE=AHIR_RELEASE+"/include"
AHIR_LIBPATH=AHIR_RELEASE + "/lib"
AJIT_HOME=os.environ['AJIT_PROJECT_HOME']
AJIT_C_REF_MODEL=os.environ['AJIT_C_REF_MODEL']

env.Append(CPPPATH = "./:" + AJIT_C_REF_MODEL + "/common/include:" + AJIT_C_REF_MODEL + "/cpu/include:" + AJIT_C_REF_MODEL + "/cpu_interface/include:"+ AJIT_C_REF_MODEL + "/memory/include:" + AJIT_C_REF_MODEL + "/IO_drivers/include:"+ AJIT_C_REF_MODEL + "/cache/include:" + AJIT_C_REF_MODEL + "/devices/include:"+ AJIT_C_REF_MODEL + "/mmu/include:" + AJIT_C_REF_MODEL + "/debugger/gpb/include:" + AJIT_C_REF_MODEL + "/debugger/hwServer/include:" + AJIT_C_REF_MODEL + "/debugger/doval/include:" + AJIT_C_REF_MODEL + "/debugger/spi_common/include:" + AJIT_HOME + "/tools/antlr3Cruntime/build/include:")

env.Append(CPPPATH = AHIR_INCLUDE + ":")

#AHIR-related
PIPE_HANDLER_INCLUDE=AHIR_RELEASE + "/include"
PIPE_HANDLER_LIBPATH = AHIR_RELEASE + "/lib"
PTHREAD_UTILS = AHIR_RELEASE + "/include"
GNU_PTH_UTILS = AHIR_RELEASE + "/include"
FUNCTIONLIB_PATH = AHIR_RELEASE + "/functionLibrary/lib"


#monitor Logger
MONITOR_LOGGER_INCLUDE=AJIT_C_REF_MODEL +'/monitorLogger/include'
MONITOR_LOGGER_LIBPATH=AJIT_C_REF_MODEL +'/monitorLogger/lib'

#Antlr related
ANTLR_PATH = AJIT_HOME + "/tools/antlr3Cruntime/build/lib "


#Need to link to Console and Char_server libraries:
CONSOLE_LIB=AJIT_HOME+"/processor/TestEnvironments/core_environment/console/lib"
CONSOLE_INCLUDE=AJIT_HOME+"/processor/TestEnvironments/core_environment/console/include"
CHAR_SERVER_LIB=AJIT_HOME+"/processor/TestEnvironments/core_environment/char_client_server/lib"
CHAR_SERVER_INCLUDE=AJIT_HOME+"/processor/TestEnvironments/core_environment/char_client_server/include"
UART_LIB=AJIT_HOME+"/processor/TestEnvironments/core_environment/uart_interface/lib"
UART_INCLUDE=AJIT_HOME+"/processor/TestEnvironments/core_environment/uart_interface/include"

env.Append(CPPPATH = UART_INCLUDE + ":" + PIPE_HANDLER_INCLUDE + ":" + PTHREAD_UTILS + ":" + GNU_PTH_UTILS + ":" + "./include:"+MONITOR_LOGGER_INCLUDE + ":" + CONSOLE_INCLUDE+ ":"+CHAR_SERVER_INCLUDE)



#ajit_C_system_model executable
LIBS=[ 'Cpu', 'CpuInterface', 'Cache', 'Mmu', 'Devices', 'Console','CharClientServer', 'Memory', 'fpu', 'Common', 'monitorLogger', 'gpb', 'pthread', 'PipeHandler', 'rt' , 'SPICommon','SockPipes', 'Hserver','doval', 'antlr3c', 'm', 'uart_interface' ] 

LIBPATH=Split('/usr/local/lib/  ../common/lib  ../memory/lib ../cache/lib ../mmu/lib ../devices/lib ../cpu/lib ../cpu_interface/lib/ ../monitorLogger/lib  ../debugger/gpb/lib ../debugger/doval/lib ../debugger/hwServer/lib ../debugger/spi_common/lib ' + ANTLR_PATH + PIPE_HANDLER_LIBPATH + "  " + FUNCTIONLIB_PATH + " " + "./lib/ "  + AHIR_LIBPATH +" "+MONITOR_LOGGER_LIBPATH+ " " + CONSOLE_LIB+ " " + CHAR_SERVER_LIB + " " + UART_LIB)

env.Program('./bin/ajit_C_system_model', './src/Ajit_C_system_testbench.c', CCFLAGS=COMPILATION_FLAGS, LINKFLAGS='-g ', LIBS=LIBS, LIBPATH=LIBPATH)
