import os
import sys
env = Environment(ENV = {'PATH' : os.environ['PATH']})



#AHIR-related
AHIR_RELEASE=os.environ['AHIR_RELEASE']
AJIT_PROJECT_HOME=os.environ['AJIT_PROJECT_HOME']
AHIR_INCLUDE=AHIR_RELEASE+"/include"
AHIR_LIBPATH=AHIR_RELEASE + "/lib"
FUNCTIONLIB_INCLUDE = AHIR_RELEASE + "/functionLibrary/include"
FUNCTIONLIB_PATH = AHIR_RELEASE + "/functionLibrary/lib"
AA_HOME=AJIT_PROJECT_HOME + "/processor/Aa_v3"
C_64_HOME=AJIT_PROJECT_HOME + "/processor/64bit/C_multi_core_multi_thread"
DOVAL_HOME=C_64_HOME+"/debugger/doval/lib"
ANTLR_PATH = AJIT_PROJECT_HOME +  "/tools/antlr3Cruntime/build/lib"


env.Append(CPPPATH = AJIT_PROJECT_HOME + '/os/kernels/pico/include:')
DEBUG_UTILS_INCLUDE=AJIT_PROJECT_HOME + '/processor/TestEnvironments/debug_utils/include'
DEBUG_UTILS_LIB=AJIT_PROJECT_HOME + '/processor/TestEnvironments/debug_utils/lib'
env.Append(CPPPATH = DEBUG_UTILS_INCLUDE + ":./src/:")

UART_LIB=AJIT_PROJECT_HOME+"/processor/TestEnvironments/core_environment/uart_interface/lib"
UART_INCLUDE=AJIT_PROJECT_HOME+"/processor/TestEnvironments/core_environment/uart_interface/include"

CONSOLE_INCLUDE=AJIT_PROJECT_HOME+"/processor/TestEnvironments/core_environment/console/include"
CONSOLE_LIB=AJIT_PROJECT_HOME+"/processor/TestEnvironments/core_environment/console/lib"

CHARSERVER_LIB=AJIT_PROJECT_HOME+"/processor/TestEnvironments/core_environment/char_client_server/lib"
CHARSERVER_INCLUDE=AJIT_PROJECT_HOME+"/processor/TestEnvironments/core_environment/char_client_server/include"

DEBUGSERVER_LIB=AJIT_PROJECT_HOME+"/processor/TestEnvironments/core_environment/debugServerMultiThread/lib"
DEBUGSERVER_INCLUDE=AJIT_PROJECT_HOME+"/processor/TestEnvironments/core_environment/debugServerMultiThread/include"

env.Append(CPPPATH = AHIR_INCLUDE + ":")
env.Append(CPPPATH = C_64_HOME + "/cpu/include:")
env.Append(CPPPATH = UART_INCLUDE + ":")
env.Append(CPPPATH = DEBUGSERVER_INCLUDE + ":")
env.Append(CPPPATH = CONSOLE_INCLUDE + ":")
env.Append(CPPPATH = CHARSERVER_INCLUDE + ":")

# debug infrastructure..
env.Append(CPPPATH = C_64_HOME + "/debugger/doval/include:" + AJIT_PROJECT_HOME + "/tools/antlr3Cruntime/build/include:" + C_64_HOME + "/debugger/spi_common/include:" + C_64_HOME + "/debugger/gpb/include:" )
env.Append(CPPPATH = C_64_HOME + "/tlbs/include/")


#===================================================================================================================
# AJIT debug monitor  
#-------------------------------------------------------------------------------------------------------------------
MONITOR_LLIBS = ' Tlbs Console rt PipeHandlerDebugPthreads Common uarch_debug_utils gpb SPICommon Common doval antlr3c fpu rt '  + ' uart_interface  '  + ' m DebugServerMT SockPipes pthread  readline Tlbs CharClientServer '  

MONITOR_LIBPATHS = ' /usr/lib/ /usr/local/lib/ ' +  C_64_HOME + '/common/lib ' +  C_64_HOME + '/debugger/gpb/lib ' + C_64_HOME + '/debugger/spi_common/lib ' +  AHIR_LIBPATH + ' ' + FUNCTIONLIB_PATH + ' ' + DEBUG_UTILS_LIB + ' ' + DOVAL_HOME  + ' ' + ANTLR_PATH + ' ' +  ' ' +   DEBUG_UTILS_LIB + ' '  +   UART_LIB  + ' '  + DEBUGSERVER_LIB + ' ' + C_64_HOME  + '/tlbs/lib '  + ' ' + CONSOLE_LIB + ' ' + CHARSERVER_LIB

env.Program('./bin/ajit_debug_monitor_mt', Split('src/ajit_debug_monitor.c src/timerRoutines.c'), CCFLAGS=' -pthread -g -DUSE_PIPE_HANDLER -DMULTICORE ' ,LINKFLAGS='-g  ', LIBS=Split(MONITOR_LLIBS), LIBPATH=Split(MONITOR_LIBPATHS))
