
#Compilation flags to be exported to all modules:
# -g  		: Compile with gdb support
# -DDEBUG 	: Enable printing debug/log messages
# -O3		: Gcc optimization level
#
# Debug support-related flags :
#
# -DHW_SERVER 	: Enable Hardware server
# -DGDB 	: Enable GDB debugging
# -DDO_VAL 	: Enable validation
# -DGDB_DBG 	: Print debugger internal communication while running


COMPILATION_FLAGS=' -g -DSW -Wall'
#COMPILATION_FLAGS=' -g -DSW -Wall -DGDB_DBG'
#COMPILATION_FLAGS=' -g -DSW -Wall -DDEBUG -DGDB_DBG '
Export('COMPILATION_FLAGS')



SConscript(['common/SConscript'])
SConscript(['cache/SConscript'])
SConscript(['memory/SConscript'])
SConscript(['mmu/SConscript'])
SConscript(['devices/SConscript'])
SConscript(['monitorLogger/SConscript'])
SConscript(['cpu_interface/SConscript'])
SConscript(['cpu/SConscript'])
SConscript(['debugger/SConscript'])
SConscript(['bridge/SConscript'])
SConscript(['rlut/SConscript'])
SConscript(['half_precision_float/SConscript'])
SConscript(['testbench/SConscript'])

