import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})
COMPILATION_FLAGS=' -g -DNVERBOSE '


AHIR_RELEASE=os.environ['AHIR_RELEASE']
AJIT_PROJECT_HOME=os.environ['AJIT_PROJECT_HOME']
UART_INCLUDE=AJIT_PROJECT_HOME + "/processor/TestEnvironments/core_environment/uart_interface/include"
env.Append(CPPPATH = './src/:./include:')

#AHIR-related
PIPE_HANDLER_INCLUDE=AHIR_RELEASE + "/include"
PIPE_HANDLER_LIBPATH = AHIR_RELEASE + "/lib"
PTHREAD_UTILS = AHIR_RELEASE + "/include"
FUNCTIONLIB_PATH = AHIR_RELEASE + "/functionLibrary/lib"
env.Append(CPPPATH = PIPE_HANDLER_INCLUDE + ":" + PTHREAD_UTILS + ":" + UART_INCLUDE + ":")

# create a library for the console :
# env.SharedLibrary('./lib/libDebugServer', Glob('src/*.c'), CCFLAGS=COMPILATION_FLAGS)
env.Library('./lib/libDebugServerMT', Glob('src/*.c'), CCFLAGS=COMPILATION_FLAGS)


