import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})
COMPILATION_FLAGS = ' -g '

env.Append(CPPPATH = './src/:./include:')
env.Library('./lib/libHalfPrecisionFloat', Glob('src/*.c'), CCFLAGS=COMPILATION_FLAGS)

LIBS=[ 'HalfPrecisionFloat']
LIBPATH=[ './lib' ]
env.Program('./bin/test_half', './util/test_half.c', CCFLAGS=COMPILATION_FLAGS, LIBS=LIBS, LIBPATH=LIBPATH);
