import os
import sys

env = Environment(ENV = {'PATH' : os.environ['PATH']})
Import('COMPILATION_FLAGS')

AHIR_RELEASE=os.environ['AHIR_RELEASE']
AHIR_INCLUDE=AHIR_RELEASE+"/include"
AHIR_LIBPATH=AHIR_RELEASE + "/lib"
AJIT_64_C_REF_MODEL=os.environ['AJIT_C_REF_MODEL']

env.Append(CPPPATH = "./:" + AJIT_64_C_REF_MODEL + "/common/include:" + AJIT_64_C_REF_MODEL + "/cpu/include:" + AJIT_64_C_REF_MODEL + "/cpu_interface/include:"+ AJIT_64_C_REF_MODEL + "/memory/include:" + AJIT_64_C_REF_MODEL + "/IO_drivers/include:"+ AJIT_64_C_REF_MODEL + "/cache/include:" + AJIT_64_C_REF_MODEL + "/devices/include:"+ AJIT_64_C_REF_MODEL + "/mmu/include:" + AJIT_64_C_REF_MODEL + "/debugger/gpb/include:" + AJIT_64_C_REF_MODEL + "/debugger/hwServer/include:" + AJIT_64_C_REF_MODEL + "/debugger/doval/include:" + AJIT_64_C_REF_MODEL + "/debugger/spi_common/include:" + AJIT_64_C_REF_MODEL + "/debugger/doval/antlr3Cruntime/build/include:")

env.Append(CPPPATH =  AJIT_64_C_REF_MODEL + "/bridge/include:")
env.Append(CPPPATH =  AJIT_64_C_REF_MODEL + "/rlut/include:")
env.Append(CPPPATH = AHIR_INCLUDE + ":")

#AHIR-related
PIPE_HANDLER_INCLUDE=AHIR_RELEASE + "/include"
PIPE_HANDLER_LIBPATH = AHIR_RELEASE + "/lib"
PTHREAD_UTILS = AHIR_RELEASE + "/include"
GNU_PTH_UTILS = AHIR_RELEASE + "/include"
FUNCTIONLIB_PATH = AHIR_RELEASE + "/functionLibrary/lib"


#monitor Logger
MONITOR_LOGGER_INCLUDE=AJIT_64_C_REF_MODEL +'/monitorLogger/include'
MONITOR_LOGGER_LIBPATH=AJIT_64_C_REF_MODEL +'/monitorLogger/lib'

# Half precision
HALFPREC_INCLUDE=AJIT_64_C_REF_MODEL +'/half_precision_float/include'
HALFPREC_LIBPATH=AJIT_64_C_REF_MODEL +'/half_precision_float/lib'

#Antlr related
ANTLR_PATH = "../debugger/doval/antlr3Cruntime/build/lib "


#Need to link to Console and Char_server libraries:
CONSOLE_LIB=AJIT_64_C_REF_MODEL+"/console/lib"
CONSOLE_INCLUDE=AJIT_64_C_REF_MODEL+"/console/include"
CHAR_SERVER_LIB=AJIT_64_C_REF_MODEL+"/char_client_server/lib"
CHAR_SERVER_INCLUDE=AJIT_64_C_REF_MODEL+"/char_client_server/include"

env.Append(CPPPATH = PIPE_HANDLER_INCLUDE + ":" + PTHREAD_UTILS + ":" + GNU_PTH_UTILS + ":" + "./include:"+MONITOR_LOGGER_INCLUDE + ":" + CONSOLE_INCLUDE+ ":"+CHAR_SERVER_INCLUDE + ":" + HALFPREC_INCLUDE)



#ajit_C_system_model executable
LIBS=[ 'Cpu', 'CpuInterface', 'Cache', 'Rlut', 'Mmu', 'Devices', 'Console','CharClientServer', 'Memory', 'fpu', 'Common', 'monitorLogger', 'gpb', 'PipeHandlerDebugPthreads', 'Bridge', 'rt' , 'SPICommon','SockPipes', 'Hserver','doval', 'antlr3c' , 'm' , 'pthread' , 'HalfPrecisionFloat'] 

LIBPATH=Split('/usr/local/lib/  ../common/lib  ../memory/lib ../cache/lib ../rlut/lib ../mmu/lib ../devices/lib ../cpu/lib ../cpu_interface/lib/ ../monitorLogger/lib  ../bridge/lib ../debugger/gpb/lib ../debugger/doval/lib ../debugger/hwServer/lib ../debugger/spi_common/lib ' + ANTLR_PATH + PIPE_HANDLER_LIBPATH + "  " + FUNCTIONLIB_PATH + " " + "./lib/ "  + AHIR_LIBPATH +" "+MONITOR_LOGGER_LIBPATH+ " " + CONSOLE_LIB+ " " + CHAR_SERVER_LIB + " "  + HALFPREC_LIBPATH)

env.Program('./bin/ajit_C_system_model', './src/Ajit_C_system_testbench.c', CCFLAGS=COMPILATION_FLAGS, LINKFLAGS='-g  ', LIBS=LIBS, LIBPATH=LIBPATH)
