import os
SConscript(['single_core/SConscript'])

env = Environment(ENV = {'PATH' : os.environ['PATH']})

AHIR_RELEASE=os.environ['AHIR_RELEASE']
AHIR_INCLUDE=AHIR_RELEASE+"/include"
AHIR_LIBPATH=AHIR_RELEASE + "/lib"
AJIT_HOME=os.environ['AJIT_PROJECT_HOME']
C_HOME=AJIT_HOME + "/processor/64bit/C_multi_core_multi_thread"

# uart_interface
UART_INTERFACE_INCLUDE=AJIT_HOME + "/processor/TestEnvironments/core_environment/uart_interface/include"

#AHIR-related
PIPE_HANDLER_INCLUDE=AHIR_RELEASE + "/include"

env.Append(CPPPATH = "./:")
env.Append(CPPPATH = UART_INTERFACE_INCLUDE + ":" + PIPE_HANDLER_INCLUDE + ":" + "./include:")
env.Append(CPPPATH = C_HOME + "/debugger/doval/include:" + C_HOME + "/debugger/doval/antlr3Cruntime/build/include:" + C_HOME + "/debugger/spi_common/include:" + C_HOME + "/debugger/gpb/include:"  + AJIT_HOME + "/tools/ajit_access_routines/include:")

# create a shared library for the environment
env.Library("./lib/uarch_debug_utils", Glob ('./src/*.c'), CCFLAGS=" -gdwarf-2 -g3 ")
