import os
import sys
env = Environment(ENV = {'PATH' : os.environ['PATH']})
env.Program('./bin/mmapToAssy', './src/mmapToAssy.c', CCFLAGS=' -g -I ./include ', LINKFLAGS='-g ')
env.Program('./bin/mmapToAssyU64', './src/mmapToAssyU64.c', CCFLAGS=' -g -I ./include ', LINKFLAGS='-g ')
env.Program('./bin/mmapToBin', './src/mmapToBin.c', CCFLAGS=' -g -I ./include ', LINKFLAGS='-g ')
